### ISSUE TITLE
Throws an error while loading

### ISSUE THREAD

**Issue by DenkingOfficial** [d8ahazard/sd_auto_fix#3]
Hey, looks like you're not checking issues frequently, but there is an important one

Log:
```
Fixing all the things!
loading stable diffusion model: AttributeError
Traceback (most recent call last):
  File "C:\Software\Other Software\sdautomatic111\webui.py", line 71, in initialize
    modules.sd_models.load_model()
  File "C:\Software\Other Software\sdautomatic111\extensions\sd_auto_fix\scripts\patch_fixer.py", line 100, in load_model
    model_config = get_config(checkpoint_info)
  File "C:\Software\Other Software\sdautomatic111\extensions\sd_auto_fix\scripts\patch_fixer.py", line 74, in get_config
    model_config = checkpoint_info.config
AttributeError: 'CheckpointInfo' object has no attribute 'config'
```

Webui commit used: [`8850fc2`](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/8850fc23b6e8a8e210bdfe4aade81516fb5770f3)

**Comment by dtlnor** [comment]
~~Fixing all the things!~~
Breaking all the things!
